view_profile:
    pattern:  /profile
    defaults: { _controller: ElleOLUserBundle:Profile:index }

logout:
    pattern: /logout

login:
    pattern:   /login
    defaults:  { _controller: ElleOLUserBundle:Security:login }

login_check:
    pattern:   /login_check