parameters:
#    elle_ol_user.example.class: ElleOL\UserBundle\Example

services:
#    elle_ol_user.example:
#        class: %elle_ol_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
