ElleOLUserBundle:
    resource: "@ElleOLUserBundle/Resources/config/routing.yml"
    prefix:   /

ElleOLAdminBundle:
    resource: "@ElleOLAdminBundle/Resources/config/routing.yml"
    prefix:   /

ElleOLSiteBundle:
    resource: "@ElleOLSiteBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
