jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        ElleOL\UserBundle\Document\User:
            algorithm:        sha512
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        customers:
            mongodb: { class: ElleOLUserBundle:User }

    firewalls:
        admin_area:
            pattern:    ^/admin
            form_login: ~
            logout: ~          
        site:
            pattern:    ^/*$
            anonymous:  ~     

    # access_control:
    #     - { path: /*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
