jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        ElleOL\UserBundle\Entity\User:
            algorithm:        sha512
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        customers:
            entity: { class: ElleOLUserBundle:User }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login: ~
            logout: true
            logout: ~

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
