ElleOLAdminBundle_homepage:
    pattern:  /admin
    defaults: { _controller: ElleOLAdminBundle:Default:index }

new_product:
    pattern: /admin/product/new
    defaults: { _controller: ElleOLAdminBundle:Product:new }
    requirements:
        _method: GET

create_product:
    pattern: /admin/product/create
    defaults: { _controller: ElleOLAdminBundle:Product:create }
    requirements:
        _method: POST

update_product:
    pattern: /admin/product/{id}/update
    defaults: { _controller: ElleOLAdminBundle:Product:update }
    requirements:
        id: \d+

delete_product:
    pattern: /admin/product/{id}/delete
    defaults: { _controller: ElleOLAdminBundle:Product:delete }
    requirements:
        id: \d+

image_upload:
    pattern: /admin/product/upload
    defaults: { _controller: ElleOLAdminBundle:Product:imageUpload }
    requirements:
        _method: POST

image_crop:
    pattern: /admin/product/upload/crop
    defaults: { _controller: ElleOLAdminBundle:Product:imageCrop }
    requirements:
        _method: POST