parameters:
#    elle_ol_admin.example.class: ElleOL\AdminBundle\Example

services:
#    elle_ol_admin.example:
#        class: %elle_ol_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
