ElleOLSiteBundle_homepage:
    pattern:  /
    defaults: { _controller: ElleOLSiteBundle:Product:index }

show_product:
    pattern: /product/{id}
    defaults: { _controller: ElleOLSiteBundle:Product:show }

about_index:
    pattern: /about
    defaults: { _controller: ElleOLSiteBundle:About:index }

contact_index:
    pattern: /contact
    defaults: { _controller: ElleOLSiteBundle:Contact:index }

custom_design_index:
    pattern: /custom
    defaults: { _controller: ElleOLSiteBundle:CustomDesign:index }

my_designs_index:
    pattern: /custom
    defaults: { _controller: ElleOLSiteBundle:MyDesign:index }
